// Autogenerated by Thrift Compiler (0.10.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
        "flag"
        "fmt"
        "math"
        "net"
        "net/url"
        "os"
        "strconv"
        "strings"
        "git.apache.org/thrift.git/lib/go/thrift"
        "cloud"
)


func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  string Login(string user, string passwd)")
  fmt.Fprintln(os.Stderr, "  string Register(string user, string passwd, string passwd2)")
  fmt.Fprintln(os.Stderr, "  string CancelLation(string user, string passwd)")
  fmt.Fprintln(os.Stderr, "  string ChangePasswd(string user, string passwd)")
  fmt.Fprintln(os.Stderr, "  string ResetPasswd(string type, string info, string code)")
  fmt.Fprintln(os.Stderr, "  string GetMainPage(string user)")
  fmt.Fprintln(os.Stderr, "  string GetUserinfo(string user)")
  fmt.Fprintln(os.Stderr, "  string GetPersons(string user)")
  fmt.Fprintln(os.Stderr, "  string GetUserConf(string user)")
  fmt.Fprintln(os.Stderr, "  string GetControlPage(string user)")
  fmt.Fprintln(os.Stderr, "  string GetVideo(string user)")
  fmt.Fprintln(os.Stderr, "  string GetMusic(string user)")
  fmt.Fprintln(os.Stderr, "  string GetForgetNote(string user)")
  fmt.Fprintln(os.Stderr, "  string GetContactNote(string user)")
  fmt.Fprintln(os.Stderr, "  string GetPictures(string user)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  var parsedUrl url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Parse()
  
  if len(urlString) > 0 {
    parsedUrl, err := url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  client := cloud.NewCloudClientFactory(trans, protocolFactory)
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "Login":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "Login requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.Login(value0, value1))
    fmt.Print("\n")
    break
  case "Register":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "Register requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.Register(value0, value1, value2))
    fmt.Print("\n")
    break
  case "CancelLation":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "CancelLation requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.CancelLation(value0, value1))
    fmt.Print("\n")
    break
  case "ChangePasswd":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "ChangePasswd requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.ChangePasswd(value0, value1))
    fmt.Print("\n")
    break
  case "ResetPasswd":
    if flag.NArg() - 1 != 3 {
      fmt.Fprintln(os.Stderr, "ResetPasswd requires 3 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    fmt.Print(client.ResetPasswd(value0, value1, value2))
    fmt.Print("\n")
    break
  case "GetMainPage":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetMainPage requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetMainPage(value0))
    fmt.Print("\n")
    break
  case "GetUserinfo":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetUserinfo requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetUserinfo(value0))
    fmt.Print("\n")
    break
  case "GetPersons":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetPersons requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetPersons(value0))
    fmt.Print("\n")
    break
  case "GetUserConf":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetUserConf requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetUserConf(value0))
    fmt.Print("\n")
    break
  case "GetControlPage":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetControlPage requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetControlPage(value0))
    fmt.Print("\n")
    break
  case "GetVideo":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetVideo requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetVideo(value0))
    fmt.Print("\n")
    break
  case "GetMusic":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetMusic requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetMusic(value0))
    fmt.Print("\n")
    break
  case "GetForgetNote":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetForgetNote requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetForgetNote(value0))
    fmt.Print("\n")
    break
  case "GetContactNote":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetContactNote requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetContactNote(value0))
    fmt.Print("\n")
    break
  case "GetPictures":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetPictures requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetPictures(value0))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
